### ISSUE TITLE
ImportError: No module named packages.urllib3.exceptions

### ISSUE THREAD

**Issue by pkpp1233** [box/box-python-sdk#57]
Looks like I'm getting a version clash on requests.

Potentially have a try / except on importing urllib3 exceptions from requests? If error, then import directly from urllib3. See here: https://github.com/locustio/locust/issues/148.

```
File "/usr/local/lib/python2.7/dist-packages/boxsdk/object/events.py", line 4, in <module>
    from requests.packages.urllib3.exceptions import TimeoutError
ImportError: No module named packages.urllib3.exceptions
```

**Comment by jmoldow** [comment]
@pkpp1233, are you relying on a requests package that has been included in Debian? If so, can you can you try ``pip install requests`` to install the official version of requests into your (virtual) environment, and see if that fixes the problem?

I don't think we should support derivative builds of requests that have changed the public namespaces.

**Comment by pkpp1233** [comment]
Hmm I'm on Ubuntu using as standard version of requests. Want me to check
that version #?

**Comment by jmoldow** [comment]
Sure, what is the version number?

The ticket you linked to, and a ticket that ticket linked to, seemed to imply to me that Debian packaged a version of requests that didn't include requests.packages, and that pip installing requests yourself and ignoring the system version of requests might fix the problem.

**Comment by pkpp1233** [comment]
requests 2.2.1

sorry for misleading ticket. it had the same error message, but likely for
a different reason.

**Comment by Jeff-Meadows** [comment]
This SDK requires requests>=2.4.3. If you upgrade to at least that version, does it fix the problem?

**Comment by Jeff-Meadows** [comment]
Closing for now since upgrading to requests>=2.4.3 should resolve this issue. If it doesn't, please feel free to reopen.

**Comment by jmoldow** [comment]
The problem with Debian / Ubuntu un-vendoring should also be improved in the upcoming requests version 2.8.0.

Though, after reading through the requests issue tracker a bunch, I'm surprised we need this import at all. requests is not supposed to bubble up any exceptions from lower-level libraries; it should be catching and re-raising them as RequestExceptions. If we're actually catching any TimeoutErrors, then that is probably a bug in requests that we should file. And if we're not, then we should instead be catching whatever exception is being raised from requests.

**Comment by Hardhik** [comment]
I get the same error as above, and when I try to upgrade, it says     

"Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS 
Successfully installed requests"

but I guess it still installed the latest version. I still get the same error. Is there any way to specify on command line to make it use the latest version. 
Thanks.

**Comment by jmoldow** [comment]
We no longer import anything from urllib3 in boxsdk, so try upgrading boxsdk.

Are you using a virtualenv? `pip install -U requests` might not work outside of a virtualenv, since requests is installed and used by the OS. If you're not already using a virtualenv, you should make one. `virtualenv YOUR_ENV_NAME && source YOUR_ENV_NAME/bin/activate && pip install -U boxsdk`.

**Comment by karinlah** [comment]
I had the same issue, on Ubuntu machine and the problem was that the Ubuntu OS is using urilib3 as well, so it didn't recognize the package installed through pip.
The solution was to remove the ubunto urllib3 package and install it again with pip:
```
apt-get remove python-urllib3 
sudo pip install urllib3 
```
